apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: emoji-propagationpolicy
  namespace: podinfo
spec:
  resourceSelectors:
    - labelSelector
        matchLabels
          app.kubernetes.io/instance: emojivoto
  placement:
    clusterAffinity:
      clusterNames:
        - cluster-1
