apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: emoji-propagationpolicy
  namespace: emojivoto
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: emoji
    - apiVersion: apps/v1
      kind: Deployment
      name: vote-bot
    - apiVersion: apps/v1
      kind: Deployment
      name: voting
    - apiVersion: apps/v1
      kind: Deployment
      name: vote-bot
    - apiVersion: apps/v1
      kind: Deployment
      name: web
    - apiVersion: v1
      kind: Service
      name: emoji-svc
  placement:
    clusterAffinity:
      clusterNames:
        - cluster-1
