apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: podinfo-propagationpolicy
  namespace: podinfo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
    - apiVersion: v1
      kind: Service
      name: podinfo
    - apiVersion: v1
      kind: Namespace
      name: podinfo
    - apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      name: podinfo
  placement:
    clusterAffinity:
      clusterNames:
        - cluster-1
