apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: metapod-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: metapod
    - apiVersion: v1
      kind: Service
      name: metapod
  placement:
    clusterAffinity:
      clusterNames:
        - cluster-1
        - cluster-2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - cluster-1
            weight: 1
          - targetCluster:
              clusterNames:
                - cluster-2
            weight: 1
