apiVersion: v1
kind: Service
metadata:
  name: game-2048
  annotations:
    service.cilium.io/global: "true"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: game-2048
